name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_push:
    path: ../
  http: 0.13.3
  flutter_local_notifications: ^8.1.1


#dependency_overrides:
#  flutter_push:
#    path: ../

dev_dependencies:
  pedantic: ^1.8.0
  drive: 1.0.0-1.0.nullsafety.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
