name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging:
    path: ../
  firebase_core: ^0.5.2+1
  http: 0.12.2
  flutter_local_notifications: ^3.0.0

#dependency_overrides:
#  firebase_core:
#    path: ../../../firebase_core/firebase_core
#  firebase_messaging:
#    path: ../
#  firebase_messaging_platform_interface:
#    path: ../../firebase_messaging_platform_interface

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
