name: flutter_push
description: Flutter plugin for FCM, HMS, xiaomi, VIVO, OPPO, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://github.com/suli1/flutter_push
version: 1.0.0-dev.4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.2
  async: ^2.4.2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
